### ISSUE TITLE
Arch-blur theme: Spotify Integration

### ISSUE THREAD

**Issue by biographie** [ngynLk/polybar-themes#4]
For some reason the spotify panel is showing offline. I can't figure out what the problem may be?
I've downloaded the spotify_status.py script from where you've suggested and installed and the libraries required. Any ideas as to what might be going on?

Thanks for your amazing themes btw!

**Comment by kiddae** [comment]
Hello, 
thank you for making this commit.
I just updated the `arch-blur` theme with another module called `playerctl`, since I forgot how that `spotify_status.py` script worked. You'll just have to get my script `playerctl_status` from my [scripts](https://github.com/ngynLk/scripts) repo and ofc `playerctl` from your package manager.
It should work well and for any player (you can set your preference in the config file).
I'm glad you like my themes, thanks :)

**Comment by biographie** [comment]
forgive me but I'm a beginner. I've copied your update config file. I've also created a file in ~/scripts called playertctl_status with the contents of your playerctl_status from from your scripts repo. playerctl is installed. 

However, polybar is now showing /bin/sh: playerctl_status: command not found

Executing the the script from the terminal produces this output:
%{T2}:%{T-} %{A1:playerctl previous -p :}%{A} %{A1:playerctl play-pause -p :}%{A} %{A1:playerctl next -p :}%{A}

surely I'm missing something trivial. I appreciate your help!

**Comment by kiddae** [comment]
You have to either add the script to your path (add `export PATH="~/scripts:$PATH"` to your `~/.profile` file and logout/login) or call the script with its absolute path from the config.

**Comment by biographie** [comment]
Thank you so much. Finally got things to work. The play and next buttons weren't showing, turns out I needed material icons.
Thanks once again!
